### ISSUE TITLE
useEffect in Container.js causes infinite loop

### ISSUE THREAD

**Issue by ssg-cnc** [Yog9/SnapShot#4]
I'd noticed that SnapShot calls flickr over and over without stopping.  You can see the problem when you bring up Chrome's developer tools and watch the network action.  To fix it, you need to change Container.js code from:

useEffect(() => {
    runSearch(searchTerm);
  }, [searchTerm, runSearch]);

to:

useEffect(() => {
    runSearch(searchTerm);
  }, [searchTerm]);

Please refer to https://medium.com/@andrewmyint/infinite-loop-inside-useeffect-react-hooks-6748de62871 for why this happens and how to solve it.

**Comment by Yog9** [comment]
@ssg-cnc I know about this issue. When I change the code to only include searchTerm in my dependency array it shows me this warning `./src/components/Container.js
  Line 10:6:  React Hook useEffect has a missing dependency: 'runSearch'. Either include it or remove the dependency array  react-hooks/exhaustive-deps`  and the build fails through travis due to the warnings. Can you suggest something so that I can get rid of the above warning. Thanks

**Comment by ssg-cnc** [comment]
I read a lot articles and experimented a little, like removing the array all together, but that just re-introduces the infinite loop problem.  I believe eslint is wrong, and so I put an ignore comment in the code: 

   useEffect(() => {
        runSearch(searchTerm);
        // eslint-disable-next-line
    }, [searchTerm]);

Even if the linter isn't wrong, a lint warning is still better than an infinite loop.

**Comment by Yog9** [comment]
Thanks @ssg-cnc :) . Disabling es-lint worked for build process of travis. This issue is fixed so I am closing it.
